import request from './index'

export const getDashboardSummary = () => request.get('/api/admin/dashboard/summary')
export const getDashboardRecent = () => request.get('/api/admin/dashboard/recent')
export const getDefinitions = () => request.get('/api/admin/definitions').then(r => r?.records ?? r)
export const getDefinitionById = (id) => request.get(`/api/admin/definitions/${id}`)
export const createDefinition = (data) => request.post('/api/admin/definitions', data)
export const updateDefinition = (id, data) => request.put(`/api/admin/definitions/${id}`, data)
export const deleteDefinition = (id) => request.delete(`/api/admin/definitions/${id}`)
export const getInstances = (params) => request.get('/api/admin/instances', { params }).then(r => r?.records ?? r ?? [])
export const getInstanceById = (id) => request.get(`/api/admin/instances/${id}`)
export const cancelInstance = (id) => request.post(`/api/admin/instances/${id}/cancel`)
export const getInstanceLogs = (id) => request.get(`/api/admin/instances/${id}/logs`)
export const createSopInstance = (data) => request.post('/api/sop/instances', data)
export const triggerSopTransition = (id, data) => request.post(`/api/sop/instances/${id}/transition`, data)
export const getJobs = (params) => request.get('/api/admin/jobs', { params }).then(r => r?.records ?? r ?? [])
export const triggerJob = (id) => request.post(`/api/admin/jobs/${id}/trigger`)
export const pauseJob = (id) => request.post(`/api/admin/jobs/${id}/pause`)
export const resumeJob = (id) => request.post(`/api/admin/jobs/${id}/resume`)
export const getArticles = (params) => request.get('/api/admin/articles', { params }).then(r => r?.records ?? r ?? [])
export const getArticleById = (id) => request.get(`/api/admin/articles/${id}`)
export const getArticlePlatforms = () => request.get('/api/admin/articles/platforms')
// Zhihu comment APIs
export const getZhihuArticle = (url) => request.get('/api/zhihu/article', { params: { url } })
export const generateComment = (data) => request.post('/api/zhihu/generate-comment', data)
export const submitCommentReview = (data) => request.post('/api/zhihu/comments/review', data)
export const getCommentReviewList = (params) => request.get('/api/zhihu/comments/review', { params }).then(r => r?.records ?? r ?? [])
export const updateCommentReview = (id, data) => request.put(`/api/zhihu/comments/review/${id}`, data)
export const publishComment = (id) => request.post(`/api/zhihu/comments/publish`, { id })
